export class Doctor {
    id: number | undefined;
    doctorName: string | undefined;
    address: string | undefined;
    degree: string | undefined;
    speciality: string | undefined;
    description: string | undefined;
    yearOfExperience: number | undefined;
    consultation_fees: number | undefined;
    clinic: Object | undefined;
    phone_number: number | undefined;
    emailId: string | undefined;
    gender: number | undefined;
    password: string | undefined;
    role: number | undefined;
    start_time: string | undefined;
    end_time: string | undefined;
    visit_duration: string | undefined;
}
